### ISSUE TITLE
Downloading from Hugging Face fails

### ISSUE THREAD

**Issue by Frnd-me** [pipixin321/HolmesVAD#15]
Following the instructions provided:

```bash
git clone https://github.com/pipixin321/HolmesVAD.git
cd HolmesVAD

conda create -n holmesvad python=3.10 -y
conda activate holmesvad

pip install --upgrade pip
pip install -e .
pip install decord opencv-python pytorchvideo
```

And subsequently running:

```bash
CUDA_VISIBLE_DEVICES=0 python demo/gradio_demo.py
```

Downloading the pre-trained model from Hugging Face fails:

```
~/.conda/envs/holmesvad/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
~/.conda/envs/holmesvad/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
~/.conda/envs/holmesvad/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "~/Projects/DPS/External/HolmesVAD/demo/gradio_demo.py", line 148, in <module>
    handler = Chat(model_path, conv_mode=conv_mode, model_base=model_base, load_8bit=load_8bit, load_4bit=load_4bit, device=device, cache_dir=cache_dir)
  File "~/Projects/DPS/External/HolmesVAD/demo/utils.py", line 48, in __init__
    self.tokenizer, self.model, processor, context_len = load_pretrained_model(model_path, model_base, model_name,
  File "~/Projects/DPS/External/HolmesVAD/videollava/model/builder.py", line 127, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "~/.conda/envs/holmesvad/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "~/.conda/envs/holmesvad/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "~/.conda/envs/holmesvad/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "~/.conda/envs/holmesvad/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "~/.conda/envs/holmesvad/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './checkpoints/HolmesVAD-7B'. Use `repo_type` argument if needed.
```

**Comment by pipixin321** [comment]
Hi, you need to download HolmesVAD-7B and place it in the ./checkpoint directory.
